import { Header } from "@/components/Header";
import { Button } from "@/components/ui/button";
import quillLogo from "@/assets/quill-logo-256x256.png";

const PrivacyPolicy = () => {
  const currentYear = new Date().getFullYear();

  return (
    <div className="min-h-screen bg-white">
      <Header />
      
      <main className="container mx-auto px-4 sm:px-8 lg:px-16 py-8 sm:py-12">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="text-center mb-8 sm:mb-12">
            <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-foreground mb-4 font-ultra-thick">
              Privacy Policy
            </h1>
            <p className="text-muted-foreground">
              Last updated: 29/09/2025
            </p>
          </div>

          {/* Content */}
          <div className="prose prose-gray max-w-none">
            <div className="space-y-6 text-foreground">
              <section>
                <h2 className="text-2xl font-bold mb-4">1. Introduction</h2>
                <p className="mb-4">
                  Welcome to Quill Limited.
                </p>
                <p className="mb-4">
                  Quill Limited ("us", "we", or "our") operates the Quill HK website (hereinafter referred to as "Service").
                </p>
                <p className="mb-4">
                  Our Privacy Policy governs your visit to our website, and explains how we collect, safeguard and disclose information that results from your use of our Service.
                </p>
                <p className="mb-4">
                  We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
                </p>
                <p className="mb-4">
                  Our Terms and Conditions ("Terms") govern all use of our Service and together with the Privacy Policy constitutes your agreement with us ("agreement").
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-4">2. Definitions</h2>
                <p className="mb-2"><strong>SERVICE</strong> means the Quill HK website operated by Quill Limited.</p>
                <p className="mb-2"><strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
                <p className="mb-2"><strong>USAGE DATA</strong> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
                <p className="mb-2"><strong>COOKIES</strong> are small files stored on your device (computer or mobile device).</p>
                <p className="mb-2"><strong>DATA CONTROLLER</strong> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
                <p className="mb-2"><strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p>
                <p className="mb-2"><strong>DATA SUBJECT</strong> is any living individual who is the subject of Personal Data.</p>
                <p className="mb-4"><strong>THE USER</strong> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-4">3. Information Collection and Use</h2>
                <p className="mb-4">
                  We collect several different types of information for various purposes to provide and improve our Service to you.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-4">4. Types of Data Collected</h2>
                <h3 className="text-xl font-semibold mb-3">Personal Data</h3>
                <p className="mb-4">
                  While using our SERVICE, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
                </p>
                <ul className="list-disc pl-6 mb-4 space-y-2">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Address, State, Province, ZIP/Postal code, City</li>
                  <li>Cookies and Usage Data</li>
                </ul>
                <p className="mb-4">
                  We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.
                </p>
                
                <h3 className="text-xl font-semibold mb-3">Usage Data</h3>
                <p className="mb-4">
                  We may also collect information that your browser sends whenever you visit our SERVICE or when you access SERVICE by or through a mobile device ("Usage Data").
                </p>
                <p className="mb-4">
                  This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our SERVICE that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
                <p className="mb-4">
                  When you access SERVICE with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-4">5. Use of Data</h2>
                <p className="mb-4">Quill Limited uses the collected data for various purposes:</p>
                <ul className="list-disc pl-6 mb-4 space-y-2">
                  <li>To notify you about changes to our Service</li>
                  <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                  <li>To provide customer support</li>
                  <li>To gather analysis or valuable information so that we can improve our Service</li>
                  <li>To monitor the usage of our Service</li>
                  <li>To detect, prevent, and address technical issues</li>
                  <li>To fulfill any other purpose for which you provide it</li>
                  <li>To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection</li>
                  <li>To provide you with notices about your account and/or subscription, including expiration and renewal notices, email instructions, etc.</li>
                  <li>To provide you with news, special offers, and general information about other goods, services, and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
                  <li>In any other way we may describe when you provide the information</li>
                  <li>For any other purpose with your consent</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-4">6. Retention of Data</h2>
                <p className="mb-4">
                  We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                </p>
                <p className="mb-4">
                  We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-4">7. Transfer of Data</h2>
                <p className="mb-4">
                  Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
                </p>
                <p className="mb-4">
                  If you are located outside Hong Kong and choose to provide information to us, please note that we transfer the data, including Personal Data, to Hong Kong and process it there.
                </p>
                <p className="mb-4">
                  Your consent to this Privacy Policy, followed by your submission of such information, represents your agreement to that transfer.
                </p>
                <p className="mb-4">
                  Quill Limited will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy, and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place, including the security of your data and other personal information.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-4">8. Disclosure of Data</h2>
                <p className="mb-4">We may disclose personal information that we collect, or you provide:</p>
                
                <h3 className="text-xl font-semibold mb-3">Disclosure for Law Enforcement</h3>
                <p className="mb-4">
                  Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.
                </p>
                
                <h3 className="text-xl font-semibold mb-3">Other cases</h3>
                <p className="mb-4">We may disclose your information also:</p>
                <ul className="list-disc pl-6 mb-4 space-y-2">
                  <li>To contractors, service providers, and other third parties we use to support our business</li>
                  <li>To fulfill the purpose for which you provide it</li>
                  <li>With your consent in any other cases</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-4">9. Security of Data</h2>
                <p className="mb-4">
                  The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-4">10. Service Providers</h2>
                <p className="mb-4">
                  We may employ third party companies and individuals to facilitate our Service ("Service Providers"), provide Service on our behalf, perform Service-related services or assist us in analyzing how our Service is used.
                </p>
                <p className="mb-4">
                  These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-4">11. Analytics</h2>
                <h3 className="text-xl font-semibold mb-3">Google Analytics</h3>
                <p className="mb-4">
                  Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.
                </p>
                <p className="mb-4">
                  For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: <a href="https://policies.google.com/privacy?hl=en" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy?hl=en</a>
                </p>
                <p className="mb-4">
                  We also encourage you to review Google's policy for safeguarding your data: <a href="https://support.google.com/analytics/answer/6004245" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">https://support.google.com/analytics/answer/6004245</a>.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-4">12. CI/CD tools</h2>
                <p className="mb-4">
                  We may use third-party Service Providers to automate the development process of our Service.
                </p>
                
                <h3 className="text-xl font-semibold mb-3">Cloudflare</h3>
                <p className="mb-4">
                  Cloudflare is a web security company that provides a cloud-based content delivery network (CDN) and security services. Cloudflare's privacy policy can be viewed at: <a href="https://www.cloudflare.com/privacypolicy/" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">https://www.cloudflare.com/privacypolicy/</a>. Our backend is hosted on Cloudflare's network.
                </p>
                
                <h3 className="text-xl font-semibold mb-3">GitHub</h3>
                <p className="mb-4">
                  GitHub is a web-based hosting service for version control of code and related documents. GitHub's privacy policy can be viewed at: <a href="https://docs.github.com/en/github/site-policy/github-privacy-statement" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">https://docs.github.com/en/github/site-policy/github-privacy-statement</a>. Github acts as our code repository.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-4">13. Payments</h2>
                <p className="mb-4">
                  We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).
                </p>
                <p className="mb-4">
                  We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
                </p>
                <p className="mb-4">The payment processors we work with are:</p>
                
                <h3 className="text-xl font-semibold mb-3">Stripe</h3>
                <p className="mb-4">
                  Their Privacy Policy can be viewed at: <a href="https://stripe.com/us/privacy" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">https://stripe.com/us/privacy</a>
                </p>
                
                <h3 className="text-xl font-semibold mb-3">Chargebee</h3>
                <p className="mb-4">
                  Their Privacy Policy can be viewed at: <a href="https://www.chargebee.com/privacy/" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">https://www.chargebee.com/privacy/</a>
                </p>
                
                <h3 className="text-xl font-semibold mb-3">LemonSqueezy</h3>
                <p className="mb-4">
                  Their Privacy Policy can be viewed at: <a href="https://www.lemonsqueezy.com/privacy" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">https://www.lemonsqueezy.com/privacy</a>
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-4">14. Third Party Services</h2>
                <h3 className="text-xl font-semibold mb-3">Supabase</h3>
                <p className="mb-4">
                  Supabase is a cloud-based database service that provides a range of database features including authentication, data storage, data processing, and data analytics. Supabase's privacy policy can be viewed at: <a href="https://supabase.com/privacy" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">https://supabase.com/privacy</a>. Supabase acts as our database and also as our authentication service.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-4">15. Cookie Policy</h2>
                <p className="mb-4">
                  Cookies are files with a small amount of data which may include an anonymous unique identifier. They are sent to your browser from a website and stored on your device.
                </p>
                
                <h3 className="text-xl font-semibold mb-3">How Quill HK Uses Cookies</h3>
                <p className="mb-4">
                  Quill HK uses cookies and similar technologies like local storage to track activity on our service and hold certain information.
                </p>
                <p className="mb-4">We distinguish between two different types of cookies:</p>
                <ul className="list-disc pl-6 mb-4 space-y-2">
                  <li><strong>Essential:</strong> Cookies that are strictly necessary for basic website or app functionality.</li>
                  <li><strong>Marketing:</strong> Cookies that are used to identify users and collect information about their behavior.</li>
                </ul>
                <p className="mb-4">Quill HK only uses essential cookies.</p>
                
                <h3 className="text-xl font-semibold mb-3">The Cookies We Set</h3>
                <p className="mb-4">
                  We use cookies provided by Supabase when you are logged in so that we can maintain your logged-in state. This prevents you from having to log in every single time you visit a new page. These cookies are removed or invalidated when you log out to ensure that users can only access certain features when logged in.
                </p>
                <p className="mb-4">
                  For more information, see the official Supabase privacy policy.
                </p>
                
                <h3 className="text-xl font-semibold mb-3">Third Party Cookies</h3>
                <p className="mb-4">
                  We use third-party payment provided by Stripe to process payments and prevent fraud.
                </p>
                <p className="mb-4">
                  For more information, see the official Stripe Cookie Policy.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-4">16. Links to Other Websites</h2>
                <p className="mb-4">
                  Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
                </p>
                <p className="mb-4">
                  We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-4">17. Children's Privacy</h2>
                <p className="mb-4">
                  Our Services are not intended for use by children under the age of 18 ("Child" or "Children").
                </p>
                <p className="mb-4">
                  We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-4">18. Changes to this Privacy Policy</h2>
                <p className="mb-4">
                  We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
                </p>
                <p className="mb-4">
                  We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update "effective date" at the top of this Privacy Policy.
                </p>
                <p className="mb-4">
                  You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-4">19. Contact Us</h2>
                <p className="mb-4">
                  If you have any questions about this Privacy Policy, please contact us:
                </p>
                <div className="bg-muted/30 p-4 rounded-lg">
                  <p><strong>By email:</strong> pedro@quill-hk.com</p>
                </div>
              </section>
            </div>
          </div>

          {/* Back to Home */}
          <div className="text-center mt-12">
            <Button asChild>
              <a href="/">Back to Home</a>
            </Button>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-muted/30 border-t border-border mt-12">
        <div className="container mx-auto px-4 sm:px-8 lg:px-16 py-4">
          <div className="flex flex-col sm:flex-row items-center justify-center gap-2 sm:gap-4 text-center">
            <div className="flex items-center gap-1">
              <img 
                src={quillLogo} 
                alt="Quill HK logo" 
                className="w-4 h-4 sm:w-5 sm:h-5"
              />
              <div className="text-[10px] sm:text-xs text-muted-foreground">
                {currentYear} Quill HK. All rights reserved.
              </div>
            </div>
              <div className="flex items-center gap-2 sm:gap-4">
                <a 
                  href="/privacy-policy" 
                  className="text-[10px] sm:text-xs text-muted-foreground hover:text-foreground transition-colors"
                >
                  Privacy Policy
                </a>
                <a 
                  href="/terms-of-service" 
                  className="text-[10px] sm:text-xs text-muted-foreground hover:text-foreground transition-colors"
                >
                  Terms of Service
                </a>
              </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default PrivacyPolicy;
